# Generated by Django 5.2.17 on 2026-08-31 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('pcs', 'Pieces'), ('lit', 'Litre'), ('ml', 'Millilitre'), ('m', 'Metre'), ('cm', 'Centimetre'), ('mm', 'Millimetre'), ('inch', 'Inch'), ('foot', 'Foot'), ('yard', 'Yard'), ('bag', 'Bag'), ('box', 'Box'), ('crate', 'Crate'), ('bunch', 'Bunch')], default='pcs', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
