# Generated by Django 5.2.17 on 2026-08-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('RWF', 'RWF (Fr)'), ('EUR', 'EUR (€)'), ('KES', 'KES (KSh)')], default='USD', max_length=10),
        ),
    ]
