# Generated by Django 5.2.17 on 2026-09-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='transaction_reference',
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, choices=[('BUGESERA', 'Bugesera'), ('BURERA', 'Burera'), ('GAKENKE', 'Gakenke'), ('GASABO', 'Gasabo'), ('GATSIBO', 'Gatsibo'), ('GISAGARA', 'Gisagara'), ('HUYE', 'Huye'), ('KAMONYI', 'Kamonyi'), ('KARONGI', 'Karongi'), ('KAYONZA', 'Kayonza'), ('KICUKIRO', 'Kicukiro'), ('KIREHE', 'Kirehe'), ('MUHANGA', 'Muhanga'), ('MUSANZE', 'Musanze'), ('NGOMA', 'Ngoma'), ('NGORORERO', 'Ngororero'), ('NYABIHU', 'Nyabihu'), ('NYAGATARE', 'Nyagatare'), ('NYAMAGABE', 'Nyamagabe'), ('NYAMASHEKE', 'Nyamasheke'), ('NYANZA', 'Nyanza'), ('NYARUGENGE', 'Nyarugenge'), ('RULINDO', 'Rulindo'), ('RUSIZI', 'Rusizi'), ('RUHANGO', 'Ruhango'), ('RUBAVU', 'Rubavu'), ('RWAMAGANA', 'Rwamagana'), ('GICUMBI', 'Gicumbi'), ('RUTSIRO', 'Rutsiro'), ('NYARUGURU', 'Nyaruguru')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Credit/Debit Card'), ('CASH_ON_DELIVERY', 'Cash on Delivery')], max_length=50),
        ),
    ]
